Initial version of the site
orcasound/orca-shipnoise pull request #1
Opened 2021-01-26 20:46 UTC by mahtabsabet

2021-02-02 08:07 UTC, scottveirs commented on README.md
> +The demo site is available at: https://main.d27wklsx9a9q36.amplifyapp.com/
This link is given just above, so probably doesn't need to be repeated here... 
(This is mostly Scott just practicing leaving a single-line comment.)

2021-02-02 08:15 UTC, scottveirs commented on src/App.js
> +      <p>Ship noise dominates the acoustic habitat of the Southern Resident Orca Whales within the Salish Sea.</p>
This should probably use the more (scientifically) conventional "Southern Resident Killer Whales" and leave "orcas" for the next line. That will be good for SEO and the two lines together will "speak" to biological experts and citizen scientists, alike.

2021-02-02 08:15 UTC, scottveirs commented on src/App.js
> +      <p>What did the orca whales hear today in Puget Sound?</p>
Switch from "orca whales" to the more commonly used "orcas" ?

2021-02-12 18:13 UTC, ivanoats requested changes
just update src/App.test.js and you're good to go 👍🏼

2021-09-16 01:13 UTC, merged